### ISSUE TITLE
Error with multiple filetypes - "Undefined variable: neomake#makers#ft#javascript"

### ISSUE THREAD

**Issue by jdelStrother** [benekastah/neomake#116]
vim-jsx recently started setting the filetype of jsx files to `javascript.jsx`, rather than plain `javascript`.  This causes neomake to fail with:

```
Error detected while processing function <SNR>53_NeomakeCommand..neomake#GetEnabledMakers:
line   14:
E121: Undefined variable: neomake#makers#ft#javascript
```

Not sure what the correct neomake behaviour should be - I'm currently working around it with this - 

```diff
diff --git a/autoload/neomake.vim b/autoload/neomake.vim
index 6aba10d..5705194 100644
--- a/autoload/neomake.vim
+++ b/autoload/neomake.vim
@@ -86,7 +86,7 @@ endfunction
 
 function! neomake#GetMaker(name_or_maker, ...) abort
     if a:0
-        let ft = a:1
+        let ft = split(a:1, '\.')[0]
     else
         let ft = ''
     endif
@@ -143,7 +143,7 @@ endfunction
 
 function! neomake#GetEnabledMakers(...) abort
     if a:0 && type(a:1) == type('')
-        let ft = a:1
+        let ft = split(a:1, '\.')[0]
     else
         let ft = ''
     endif
```

I can submit a PR for this if you like, but I suppose an ideal implementation might loop over all the filetypes in 'ft' and try to find enabled makers for each of them.

**Comment by benekastah** [comment]
Interesting. I didn't realize filetypes would ever have non-identifier characters. Should have read the docs more carefully first, I suppose. Yes, I suppose it does make sense to find makers for each dot-separated filetype.

In this specific case, we are going to run into problems. `jshint` will report errors on jsx files because it can't parse them, so people using `jsxhint` are going to get invalid errors reported. So in addition to using all filetypes to find makers, we are going to have to have a way to filter out makers that don't apply to all filetypes. I don't have a good way to do that off the top of my head, but suggestions (and pull requests) welcome.

**Comment by jdelStrother** [comment]
Oh, I hadn't run into that - I just use eslint for both, and up till now was relying on `let g:neomake_javascript_enabled_makers = ['eslint']` to cover both javascript & jsx files, since they both had a `javascript` filetype.

**Comment by benekastah** [comment]
Can eslint parse Jax files without errors?

**Comment by jdelStrother** [comment]
Yep, as of version 0.11

**Comment by benekastah** [comment]
Interesting. Well, I think I know how I'd like to approach this now. A maker will be run if and only if it is listed in the enabled makers list for every filetype. So jshint will only be in the javascript list, but jsxhint and eslint will be in the javascript and jsx list. It might also be nice to be able to reference makers for other filetypes so we don't have a whole bunch of duplicate makers.

**Comment by jdelStrother** [comment]
Sounds good.
