### ISSUE TITLE
Custom preprocessing function

### ISSUE THREAD

**Issue by kirelagin** [benekastah/neomake#138]
Let’s be honest, `errorformat` is horrible.

It would be great if it was easy to create a maker that passes obtained output to a custom function (probably even written in Python) that transforms the output into something parsable with `errorformat`.

That’s somewhat related to #111 as this is something similar to `mapexpr` (to be honest, I fail to see how `mapexpr` can be useful in presence of multiline error messages).

**Comment by benekastah** [comment]
I don't like errorformats much myself, especially for multiline error messages. But I don't know if I love writing custom code to parse errorformats. I don't want to maintain code like that for one. As terrible as errorformats are, they are well documented and usually don't required my personal attention to fix. Especially since syntastic has tons of great errorformats that we can use if ours break.

If some maker (like `cargo` for example) doesn't produce output that is easy to parse with an errorformat, you can submit a pull request to `cargo` to add an option to output something easy to parse (like CSV) instead. Alternately, you could write a wrapper program that takes `cargo`'s output, parses it, and spits it out in some other format. Then you could add that as its own maker in this project.

**Comment by kirelagin** [comment]
Hm, I am just asking for a hook to let maker specifications authors add a bit of custom preprocessing. This won’t require you to write or maintain any additional code (well, except for the code in neomake that will invoke the preprocessor if it is configured for the maker).

The wrapper idea is a nice one, and it’s probably the way to go. I’ll give it a shot, thanks!

**Comment by kirelagin** [comment]
Well, since the wrapper thing is actually a fully functional replacement for what I was asking for, I guess, this can be closed.
