### ISSUE TITLE
How to make it work instead of Syntastic?

### ISSUE THREAD

**Issue by firedev** [benekastah/neomake#166]
Hi,

I am trying to start from scratch with Neovim and this is the first plugin I am trying to install. I have rubocop and everything in my Vim configuration working. So I do

```
:set ft=ruby
:set makreprg=rubocop
:Neomake!
Neomake: makeprg complete with exit code 0
```

`:copen` is empty as well.

What should I do to make it work?

**Comment by firedev** [comment]
After adding it to autogroup it works. Maybe this should be reflected in docs?

**Comment by benekastah** [comment]
The [readme mentions this solution](https://github.com/benekastah/neomake#how-to-use-basic). Did you have to do something else that you think should be in the docs?

**Comment by firedev** [comment]
Hi, the thing is - it didn't do anything at all when I was issuing  `:Neomake` command until I have added it to `autocmd`. I don't know if it is something on my end or `autocmd` is required.

**Comment by benekastah** [comment]
Using an autocommand isn't required to get things working. What does your autocommand look like? Possibly you're using `:Neomake` (useful for operating on the current file) instead of `:Neomake!` (useful for collecting the results of the whole project).

Also, using the makeprg from your origial post, what output do you get when you run `:make`? Maybe `rubocop` just needs more arguments? If there's a difference then it's a bug that should be fixed.

**Comment by blueyed** [comment]
@firedev 
Can you provide more input?
Otherwise this issue should probably get closed.

**Comment by firedev** [comment]
Yes, sorry, I am closing this, it works now.
