### ISSUE TITLE
Typescript linting not running?

### ISSUE THREAD

**Issue by mhartington** [benekastah/neomake#172]
So I'm probably doing something wrong, but just incase....

I have `tslint` install globally 

```
sudo npm i -g tslint
```

Then setup my lint with neomake like so.

```
  let g:neomake_typescript_tslint_maker = {
  \ 'args': ['--verbose'],
  \ 'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)',
  \ }
  let g:neomake_typescript_enabled_makers = ['tslint']
```

But nothing shows, event though I know there are errors in a file.
Running tslint against the file shows errors.

**Comment by benekastah** [comment]
Go to the file you want to lint and make sure that `:echo &ft` is "typescript". If not, you will need to modify the names of the variables (e.g. `g:neomake_tscript_tslint_maker` if it is tslint).

Next, run `:Neomake` (not `:Neomake!`, which is meant to operate on many files rather than just the one you are currently editing). You should get the right output at this point. If you want the errors to show up when you save the file, then you need to make an autocommand for it yourself (see the [readme](https://github.com/benekastah/neomake#how-to-use-basic) for instructions).

Let me know what happens when you try that. If all those things are in order, I'll need more info from you as to what exactly you did so I can figure out how to resolve it.

**Comment by mhartington** [comment]
Went ahead and tried that, still nothing. The ft is being set correctly to `typescript`, so thats good.

But funny enough, if you just use the built in makers, tscs and tslint, everything works fine. Not sure if that helps

**Comment by benekastah** [comment]
Interesting. Is this issue resolved for you, then?

**Comment by mhartington** [comment]
Yeah I think we can call this resolved

**Comment by conor-mac-aoidh** [comment]
Seeing the same issue - configuring settings for tslint as described in the readme does not seem to work. This is what I have currently:

```
let g_neomake_typescript_tslint_maker = {
  \ 'exe': 'tslint',
  \ 'args': ['-r', '/usr/local/lib/node_modules/tslint-jsdoc-rules/lib', '--experimentalDecorators']
  \ }
let g:neomake_typescript_enabled_makers = ['tslint']
```

The above produces no output. However, making the same changes to the typescript.vim file does work:

```
function! neomake#makers#ft#typescript#tslint() abort
    return {
        \ 'args': [
            \ '%:p', '--format verbose',
            \ '--experimentalDecorators',
            \ '-r', '/usr/local/lib/node_modules/tslint-jsdoc-rules/lib'
        \ ],
        \ 'errorformat': '%f[%l\, %c]: %m'
        \ }
```

Any idea why the former approach is not working?

**Comment by blueyed** [comment]
@conor-mac-aoidh 
You are missing the `'%:p', '--format verbose',` args, and also the `errorformat`.
And then `let g_neomake_typescript_tslint_maker` is wrong: you need `g:`, not `g_`.
But instead of overwriting the maker completely, you can also just change its args:
`let g:neomake_typescript_tslint_args = […]`

**Comment by conor-mac-aoidh** [comment]
@blueyed ah damn I knew it would be something simple! Now using `let g:neomake_typescript_tslint_args = […]` and working without issue. Cheers!
