### ISSUE TITLE
Issue with creating new makers

### ISSUE THREAD

**Issue by natemara** [benekastah/neomake#32]
I am trying to create a new maker for python that doesn't complain about tabs in the whitespace. I have used the following snippet, based on the [readme](https://github.com/benekastah/neomake/blob/master/README.md#how-to-use-advanced), but I am being met with errors.

```vim
let g:neomake_pep8alt_maker = {
    \ 'exe': 'pep8',
    \ 'args': ['--ignore=W191'],
    \ 'errorformat': '%f:%l:%c: %m',
    \ }

let g:neomake_python_enabled_makers = ['pep8alt', 'pylint']
```

When I run `:Neomake` from a python file, I get the error:

```
command not found: pep8alt
```

What is going on here? Has the maker API changed since the readme was written, or did I just miss something?

**Comment by benekastah** [comment]
I think changing `g:neomake_pep8alt_maker` to `g:neomake_python_pep8alt_maker` will do the trick. It can't find it currently because it only looks for filetype-specific makers when running `:Neomake` (without the exclamation point).

I may need to clarify the language in the docs, because I feel like with the current api the difference between `:Neomake` and `:Neomake!` could be confusing. Suggestions welcome.

Also, perhaps it would be good to search for a filetype specific maker first, and failing that try to find a general maker (though I'm not sure what kind of utility would be run on any filetype).

Let me know if that works for you.

**Comment by natemara** [comment]
That solved the issue. Thanks

**Comment by benekastah** [comment]
I made #33 to improve docs for this feature. Glad it's working for you!
