### ISSUE TITLE
Add Quickfix/Location List Settings

### ISSUE THREAD

**Issue by prikhi** [benekastah/neomake#39]
Coming from Syntastic, I miss these options:
* `syntastic_auto_loc_list` - pop open the loc list if any errors exist
* `syntastic_loc_list_height` - control the max height of the loc list
* `syntastic_check_on_wq` - this prevents a checking delay when trying to quit

I would love it if these could be added, or maybe there is a way to achieve all
this already?

**Comment by benekastah** [comment]
Addressing these in order:

  - Have a look at `g:neomake_open_list`. I haven't used this recently because it seems to trigger bug #17 a lot, unfortunately.
  - Having a height setting would certainly make sense to go along with the above setting. You can, of course, do `:copen [height]` or `:lopen [height]` for yourself until that feature gets added. It should be pretty easy to add.
- Have you run into problems on `wq`? Since neomake checks asynchronously, quitting should just cancel any jobs that are running, but I haven't done a specific test.

**Comment by prikhi** [comment]
* I tried it and noticed it. Mostly hurts on `:wa`, otherwise a quick `ctrl-o` is better than waiting around for syntastic to finish :)
* Cool thanks for the `lopen` tip.
* I did one time before I posted the above, but haven't since, so I'm thinking I had accidently opened up vim instead of neovim.

**Comment by benekastah** [comment]
By the way, `g:neomake_open_list` should work a bit better now since #17 has been fixed.

**Comment by prikhi** [comment]
Thanks, I've pulled the latest version and seems to be working fine :)

**Comment by benekastah** [comment]
It seems like everything here has been addressed. I'm not sure if I want to worry about the `:wq` issue, but if it's still a problem please open a new issue just for that. Thanks!

**Comment by prikhi** [comment]
Hell yeah for awesome plugins :)

**Comment by benekastah** [comment]
:)
