### ISSUE TITLE
How to run Neomake silently?

### ISSUE THREAD

**Issue by trusktr** [benekastah/neomake#67]
I tried `:silent Neomake` but it still shows things like `Neomake: jshint complete`.

**Comment by benekastah** [comment]
The only way to do this currently is to do something like this:

```
let g:neomake_verbose = 0
```

Keep in mind, that approach will still show errors. If you want to turn those off as well, then use `-1` instead of `0`.

Unfortunately there isn't a way to do this currently on a per-call basis. Read `:help g:neomake_verbose` for more info if you need it.

**Comment by benekastah** [comment]
I'll leave this open for now to remind me to see how hard it would be to get this working with `silent`.

**Comment by trusktr** [comment]
Maybe it can take an arg, f.e. `:Neomake silent`, if that's easier?

**Comment by benekastah** [comment]
This would require significant refactoring to do right unfortunately. Maybe it can be revisited later, but I'm not going to worry about it for now.

**Comment by snoblenet** [comment]
Does the `-1` option still work? It's not mentioned in the documentation and it doesn't seem to be working for me.
