### ISSUE TITLE
Neomake not expanding %

### ISSUE THREAD

**Issue by ViViDboarder** [benekastah/neomake#68]
I set my makeprg set to `echo\ %` and running `:make` works just fine and I can see it execute `echo path/to/file` and `:copen` shows `path/to/file`, but when I run `:Neomake!` it doesn't appear to find the file. and `:copen` shows `%`.

So it appears that the `%` is not being expanded but is being treated literally. Is there something simple I'm missing?

**Comment by benekastah** [comment]
Neomake doesn't currently attempt to expand anything. However, to get `%`, you can do this instead:

```
let g:neomake_python_echo_maker = {
    \ 'exe': 'echo',
    \ 'args': [],
    \ 'errorformat': &errorformat,
    \ }
```

And then run `:Neomake` (note: no exclamation point). With `:Neomake`, the current file is appended to the arguments list before the job is run and the results are placed in the location list instead of the quickfix list, so you can see them by running `:lopen` instead of `:copen`.

**Comment by ViViDboarder** [comment]
Ok, I'll try that. Thanks.

I'm new to Neovim (and Neomake), so maybe this is stupid, but is the not expanding because Neovim can't, because it just hasn't been implemented yet, or because it was a design choice to intentionally not do it?

If you're open to an implementation of it I may give it a shot.

**Comment by benekastah** [comment]
When I was first coding this up it seemed to add more complexity than I wanted to deal with at the time. I haven't looked into it since. I'd be open to an implementation if there was a fairly simple way to do it.
