### ISSUE TITLE
Feature Request: Add ability to execute arbitrary commands

### ISSUE THREAD

**Issue by ViViDboarder** [benekastah/neomake#79]
So, this is definitely not a bug but rather a request that mimics a bit how :Dispatch works.

You've done a great job and a lot of groundwork for executing arbitrary shell commands and tracking and displaying the results with jobs. In one of my plugins I've been trying to do something similar and I'm ending up writing a lot of the same stuff you have already done.

It would be great to do something like `:Neomake do foo bar` and have it work the same way `:! do foo bar` or `:Dispatch do foo bar` do.

If this is something you're open to I can give it a shot myself instead of doing it in my plugin.

**Comment by benekastah** [comment]
I've thought about this before. At one point it was my intention to build a way to use "anonymous makers", something like this:

```
call neomake#Make({
    \ 'enabled_makers': [{
        \ 'exe': 'cat',
        \ 'args': ['/proc/cpuinfo'],
        \ 'errorformat': &efm
    \ }]
\ })
```

Notice that instead of passing in the name of an enabled maker, I'm passing in an object that represents a maker I made on the fly. This doesn't currently work, but from that point I think it would be possible to write a nice interface around it. My only concern with adding this functionality is that it feels a bit like feature creep. That said, I'm interested in having this functionality myself, and it probably wouldn't be too hard to implement on top of what we've got already. As long as it's not likely to generate a large maintenance cost I think I'm for it.

**Comment by ViViDboarder** [comment]
Yea, I made a small change that allowed me to do `:Neomake {'exe':'foo','args':['bar','baz']}` and it works ok. Not perfect though because any spaces break it.

https://github.com/ViViDboarder/neomake/commit/8d6a813ec474b866da04d68305c1bf9832cbe369

I can start a PR if and we can discuss there if this is going down the right path.

**Comment by benekastah** [comment]
I actually think this should be done with a different command, because otherwise parsing command arguments will be really tricky. Then we won't have to detect objects ourselves either. Maybe something like `:NeomakeSh foo bar baz` could build an anonymous maker with that executable and arguments and run it.

**Comment by ViViDboarder** [comment]
Yea. That'd be way less complicated. I'll try building that out.

**Comment by ViViDboarder** [comment]
Replaced by #80
